export const Errors = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  NAME_TOO_SHORT: 'NAME_TOO_SHORT',
  ID_INVALID: 'ID_INVALID',
  NAME_EMPTY: 'NAME_EMPTY',
  NAME_TOO_LONG: 'NAME_TOO_LONG',
  SURNAME_REQUIRED: 'SURNAME_REQUIRED',
  NAME_NOT_CHARACTERS: 'NAME_NOT_CHARACTERS',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
  INVALID_HASH_PASSWORD: 'INVALID_HASH_PASSWORD',
  NEGATIVE_DURATION: 'NEGATIVE_DURATION',
  URL_INVALID: 'URL_INVALID',
} as const;
